spring.application.name=productos
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/productos_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

#URLs para WebClient
usuarios-service.url=http://localhost:8081/usuarios
categorias-service.url=http://localhost:8090/categorias
productos-service.url=http://localhost:8082/productos